### ISSUE TITLE
Creating a product -> plan is broken

### ISSUE THREAD

**Issue by pgroot91** [superdav42/wp-multisite-waas#144]
```
[06-Aug-2025 20:30:15 UTC] PHP Fatal error:  Uncaught TypeError: WP_Ultimo\Models\Product::set_price_variations(): Argument #1 ($price_variations) must be of type ?array, string given in /var/www/html/wp-content/plugins/wp-multisite-waas/inc/models/class-product.php:1266
Stack trace:
#0 [internal function]: WP_Ultimo\Models\Product->set_price_variations('')
#1 /var/www/html/wp-content/plugins/wp-multisite-waas/inc/models/class-base-model.php(266): call_user_func(Array, '')
#2 /var/www/html/wp-content/plugins/wp-multisite-waas/inc/admin-pages/class-edit-admin-page.php(833): WP_Ultimo\Models\Base_Model->load_attributes_from_post()
#3 /var/www/html/wp-content/plugins/wp-multisite-waas/inc/admin-pages/class-product-edit-admin-page.php(1114): WP_Ultimo\Admin_Pages\Edit_Admin_Page->handle_save()
#4 /var/www/html/wp-content/plugins/wp-multisite-waas/inc/admin-pages/class-edit-admin-page.php(225): WP_Ultimo\Admin_Pages\Product_Edit_Admin_Page->handle_save()
#5 /var/www/html/wp-content/plugins/wp-multisite-waas/inc/admin-pages/class-edit-admin-page.php(102): WP_Ultimo\Admin_Pages\Edit_Admin_Page->process_save()
#6 /var/www/html/wp-includes/class-wp-hook.php(324): WP_Ultimo\Admin_Pages\Edit_Admin_Page->page_loaded('')
#7 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#8 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /var/www/html/wp-admin/admin.php(238): do_action('load-admin_page...')
#10 /var/www/html/wp-admin/network/admin.php(13): require_once('/var/www/html/w...')
#11 {main}
  thrown in /var/www/html/wp-content/plugins/wp-multisite-waas/inc/models/class-product.php on line 1266
```

**Comment by superdav42** [comment]
I'm pretty sure this is related to #141. So it's fixed in the main branch.

**Comment by pgroot91** [comment]
@superdav42 i'm pretty sure i'm on main and in sync. 

Are you also aware the tests are also still failing on the main branch?

**Comment by pgroot91** [comment]
@superdav42 this seems to fixed will close it!

**Comment by superdav42** [comment]
> [@superdav42](https://github.com/superdav42) i'm pretty sure i'm on main and in sync.
> 
> Are you also aware the tests are also still failing on the main branch?

Thanks for pointing that out. I reverted [Prevent extra queries and site changes](https://github.com/superdav42/wp-multisite-waas/commit/a084bb9b1eaec09f4b57e9d7c5066a6d0222ae7e) So now main is stable again. Something weird is happening in that legacy code. I'll need to figure out what it is.
